/home/parallels/Desktop/fault_attack_program/attack/Main.o /home/parallels/Desktop/fault_attack_program/attack/Main.or /home/parallels/Desktop/fault_attack_program/attack/Main.od /home/parallels/Desktop/fault_attack_program/attack/Main.op: /home/parallels/Desktop/fault_attack_program/attack/Main.cc \
 /home/parallels/Desktop/fault_attack_program/simp/SimpSolver.h \
 /home/parallels/Desktop/fault_attack_program/mtl/Queue.h \
 /home/parallels/Desktop/fault_attack_program/mtl/Vec.h \
 /home/parallels/Desktop/fault_attack_program/mtl/IntTypes.h \
 /home/parallels/Desktop/fault_attack_program/mtl/XAlloc.h \
 /home/parallels/Desktop/fault_attack_program/core/Solver.h \
 /home/parallels/Desktop/fault_attack_program/mtl/Heap.h \
 /home/parallels/Desktop/fault_attack_program/mtl/Alg.h \
 /home/parallels/Desktop/fault_attack_program/utils/Options.h \
 /home/parallels/Desktop/fault_attack_program/utils/ParseUtils.h \
 /home/parallels/Desktop/fault_attack_program/core/SolverTypes.h \
 /home/parallels/Desktop/fault_attack_program/mtl/Map.h \
 /home/parallels/Desktop/fault_attack_program/mtl/Alloc.h \
 /home/parallels/Desktop/fault_attack_program/Parser/attack_parser.h \
 /home/parallels/Desktop/fault_attack_program/Parser/netlist_parser.h \
 /home/parallels/Desktop/fault_attack_program/utils/dict.h \
 /home/parallels/Desktop/fault_attack_program/utils/tools.h \
 /home/parallels/Desktop/fault_attack_program/Parser/parser.h \
 /home/parallels/Desktop/fault_attack_program/Parser/fault_parser.h \
 /home/parallels/Desktop/fault_attack_program/attack/constructor.h \
 /home/parallels/Desktop/fault_attack_program/MUX/gate.h \
 /home/parallels/Desktop/fault_attack_program/MUX/MUX.h \
 /home/parallels/Desktop/fault_attack_program/CNF/Attack_CNF_handler.h \
 /home/parallels/Desktop/fault_attack_program/CNF/CNF_handler.h \
 /home/parallels/Desktop/fault_attack_program/solver/SAT.h \
 /home/parallels/Desktop/fault_attack_program/utils/System.h \
 /home/parallels/Desktop/fault_attack_program/core/Dimacs.h \
 /home/parallels/Desktop/fault_attack_program/solver/print_solution.h \
 /home/parallels/Desktop/fault_attack_program/Parser/Parse_result.h
